services:
  api-gateway:
    container_name: api-gateway
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
      target: development
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    ports:
      - '3000:3000'
    env_file:
      - path: .env
        required: true
      - path: ./apps/api-gateway/.env
        required: false
    environment:
      - NODE_ENV=development
      - PORT=3000
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - taskhub-network
    develop:
      watch:
        - action: sync
          path: ./apps/api-gateway/
          target: /taskhub/apps/api-gateway/

        - action: rebuild
          path: ./apps/api-gateway/package.json
        - action: rebuild
          path: ./apps/api-gateway/Dockerfile
        - action: rebuild
          path: .dockerignore
  auth-service:
    container_name: auth-service
    tty: true
    build:
      context: .
      dockerfile: ./apps/auth-service/Dockerfile
      target: development
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    env_file:
      - path: .env
        required: true
      - path: ./apps/auth-service/.env
        required: false
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - taskhub-network
    develop:
      watch:
        - action: sync
          path: ./apps/auth-service/
          target: /taskhub/apps/auth-service/

        - action: rebuild
          path: ./apps/auth-service/package.json
        - action: rebuild
          path: ./apps/auth-service/Dockerfile
        - action: rebuild
          path: .dockerignore

  postgres:
    image: postgres:18.1-alpine
    container_name: postgres
    attach: false
    ports:
      - '5432:5432'
    networks:
      - taskhub-network
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}

  rabbitmq:
    image: rabbitmq:4.2.1-management-alpine
    container_name: rabbitmq
    attach: false
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - taskhub-network
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes: [ 'rabbitmq_data:/var/lib/rabbitmq' ]

volumes:
  postgres_data:
    driver: local
  rabbitmq_data:
    driver: local

networks:
  taskhub-network:
    driver: bridge
